<?php 
return array (
  'id' => 'int',
  'member_id' => 'int',
  'name' => 'string',
  'mobile' => 'string',
  'telephone' => 'string',
  'province_id' => 'int',
  'city_id' => 'int',
  'district_id' => 'int',
  'community_id' => 'int',
  'address' => 'string',
  'full_address' => 'string',
  'longitude' => 'string',
  'latitude' => 'string',
  'is_default' => 'int',
  'type' => 'int',
  '_pk' => 'id',
  '_autoinc' => 'id',
);