<?php 
return array (
  'bargain_id' => 'int',
  'site_id' => 'int',
  'site_name' => 'string',
  'goods_id' => 'int',
  'sku_id' => 'int',
  'bargain_name' => 'string',
  'is_fenxiao' => 'int',
  'buy_type' => 'int',
  'bargain_type' => 'int',
  'bargain_num' => 'int',
  'bargain_time' => 'int',
  'remark' => 'string',
  'create_time' => 'int',
  'modify_time' => 'int',
  'start_time' => 'int',
  'end_time' => 'int',
  'status' => 'int',
  'status_name' => 'string',
  'is_own' => 'int',
  'sale_num' => 'int',
  'join_num' => 'int',
  'bargain_stock' => 'int',
  'floor_price' => 'float',
  '_pk' => 'bargain_id',
  '_autoinc' => 'bargain_id',
);