<?php 
return array (
  'id' => 'int',
  'withdraw_no' => 'string',
  'site_id' => 'int',
  'site_name' => 'string',
  'name' => 'string',
  'mobile' => 'string',
  'bank_type' => 'int',
  'settlement_bank_account_name' => 'string',
  'settlement_bank_account_number' => 'string',
  'settlement_bank_name' => 'string',
  'settlement_bank_address' => 'string',
  'money' => 'float',
  'apply_time' => 'int',
  'payment_time' => 'int',
  'status' => 'int',
  'memo' => 'string',
  'modify_time' => 'int',
  'is_period' => 'int',
  'period_id' => 'int',
  'period_name' => 'string',
  'paying_money_certificate' => 'string',
  'paying_money_certificate_explain' => 'string',
  '_pk' => 'id',
  '_autoinc' => 'id',
);