<?php 
return array (
  'company_id' => 'int',
  'company_name' => 'string',
  'logo' => 'string',
  'url' => 'string',
  'sort' => 'int',
  'express_no_kdniao' => 'string',
  'express_no_kd100_free' => 'string',
  'express_no_kd100' => 'string',
  'express_no_cainiao' => 'string',
  'express_no_ext' => 'string',
  'content_json' => 'string',
  'background_image' => 'string',
  'font_size' => 'string',
  'width' => 'string',
  'height' => 'string',
  'create_time' => 'int',
  'modify_time' => 'int',
  'scale' => 'float',
  'is_electronicsheet' => 'int',
  'print_style' => 'string',
  '_pk' => 'company_id',
  '_autoinc' => 'company_id',
);