<?php 
return array (
  'id' => 'int',
  'type' => 'int',
  'type_name' => 'string',
  'type_id' => 'int',
  'name' => 'string',
  'image' => 'string',
  'stock' => 'int',
  'point' => 'int',
  'market_price' => 'float',
  'price' => 'float',
  'delivery_price' => 'float',
  'balance' => 'float',
  'state' => 'int',
  'content' => 'string',
  'create_time' => 'int',
  'modify_time' => 'int',
  'pay_type' => 'int',
  'sort' => 'int',
  'sales_volume' => 'int',
  'set_volume' => 'int',
  'time' => 'int',
  'explain' => 'string',
  '_pk' => 'id',
  '_autoinc' => 'id',
);