<?php 
return array (
  'platformcoupon_type_id' => 'int',
  'platformcoupon_name' => 'string',
  'money' => 'float',
  'count' => 'int',
  'lead_count' => 'int',
  'max_fetch' => 'int',
  'at_least' => 'float',
  'end_time' => 'int',
  'image' => 'string',
  'create_time' => 'int',
  'update_time' => 'int',
  'validity_type' => 'int',
  'fixed_term' => 'int',
  'status' => 'int',
  'is_show' => 'int',
  'use_scenario' => 'int',
  'group_ids' => 'string',
  'platform_split_rare' => 'float',
  'shop_split_rare' => 'float',
  '_pk' => 'platformcoupon_type_id',
  '_autoinc' => 'platformcoupon_type_id',
);