<?php 
return array (
  'order_id' => 'int',
  'site_id' => 'int',
  'site_name' => 'string',
  'order_no' => 'string',
  'out_trade_no' => 'string',
  'cover_img' => 'string',
  'face_value' => 'float',
  'buy_price' => 'float',
  'point' => 'int',
  'growth' => 'int',
  'coupon_id' => 'string',
  'price' => 'float',
  'pay_type' => 'string',
  'pay_type_name' => 'string',
  'status' => 'string',
  'create_time' => 'int',
  'pay_time' => 'int',
  'member_id' => 'int',
  'nickname' => 'string',
  'order_from' => 'string',
  'order_from_name' => 'string',
  '_pk' => 'order_id',
  '_autoinc' => 'order_id',
);