<?php 
return array (
  'id' => 'int',
  'site_id' => 'int',
  'order_id' => 'int',
  'order_goods_id_array' => 'string',
  'goods_id_array' => 'string',
  'package_name' => 'string',
  'delivery_type' => 'int',
  'express_company_id' => 'int',
  'express_company_name' => 'string',
  'delivery_no' => 'string',
  'delivery_time' => 'int',
  'member_id' => 'int',
  'member_name' => 'string',
  'express_company_image' => 'string',
  'type' => 'string',
  'template_id' => 'int',
  'template_name' => 'string',
  '_pk' => 'id',
  '_autoinc' => 'id',
);