<?php 
return array (
  'id' => 'int',
  'addon' => 'string',
  'keywords' => 'string',
  'title' => 'string',
  'message_type' => 'int',
  'message_json' => 'string',
  'email_is_open' => 'int',
  'email_title' => 'string',
  'email_content' => 'string',
  'sms_is_open' => 'int',
  'sms_addon' => 'string',
  'sms_json' => 'string',
  'sms_content' => 'string',
  'wechat_is_open' => 'int',
  'wechat_json' => 'string',
  'weapp_is_open' => 'int',
  'weapp_json' => 'string',
  'aliapp_is_open' => 'int',
  'aliapp_json' => 'string',
  'support_type' => 'string',
  '_pk' => 'id',
  '_autoinc' => 'id',
);