<?php 
return array (
  'id' => 'int',
  'settlement_no' => 'string',
  'site_id' => 'int',
  'period_id' => 'int',
  'site_name' => 'string',
  'order_money' => 'float',
  'shop_money' => 'float',
  'refund_platform_money' => 'float',
  'platform_money' => 'float',
  'refund_shop_money' => 'float',
  'refund_money' => 'float',
  'create_time' => 'int',
  'period_start_time' => 'int',
  'period_end_time' => 'int',
  'commission' => 'float',
  'website_id' => 'int',
  'website_commission' => 'float',
  'settlement_id' => 'int',
  'platform_coupon_money' => 'float',
  'refund_platform_coupon_money' => 'float',
  '_pk' => 'id',
  '_autoinc' => 'id',
);