<?php 
return array (
  'pintuan_id' => 'int',
  'site_id' => 'int',
  'site_name' => 'string',
  'pintuan_name' => 'string',
  'goods_id' => 'int',
  'is_virtual_goods' => 'int',
  'pintuan_num' => 'int',
  'pintuan_time' => 'int',
  'remark' => 'string',
  'create_time' => 'int',
  'modify_time' => 'int',
  'is_recommend' => 'int',
  'start_time' => 'int',
  'end_time' => 'int',
  'buy_num' => 'int',
  'pintuan_price' => 'float',
  'is_single_buy' => 'int',
  'is_virtual_buy' => 'int',
  'is_promotion' => 'int',
  'status' => 'int',
  'group_num' => 'int',
  'success_group_num' => 'int',
  'order_num' => 'int',
  '_pk' => 'pintuan_id',
  '_autoinc' => 'pintuan_id',
);