<?php 
return array (
  'card_id' => 'int',
  'recharge_id' => 'int',
  'site_id' => 'int',
  'site_name' => 'string',
  'card_account' => 'string',
  'recharge_name' => 'string',
  'cover_img' => 'string',
  'face_value' => 'float',
  'point' => 'int',
  'growth' => 'int',
  'coupon_id' => 'string',
  'buy_price' => 'float',
  'member_id' => 'int',
  'member_img' => 'string',
  'nickname' => 'string',
  'order_id' => 'int',
  'order_no' => 'string',
  'from_type' => 'int',
  'use_status' => 'int',
  'create_time' => 'int',
  'use_time' => 'int',
  '_pk' => 'card_id',
  '_autoinc' => 'card_id',
);